### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by pbassut** [django-ckeditor/django-ckeditor#211]
Looks like the pip package is very outdated. I don't know how you guys are making releases but I can't find them here on GitHub. 
I just wanted to point out that the pip package is very outdated and without some core stuff(extra plugins, for example. Mainly mathjax).

**Comment by riklaunim** [comment]
Changes from recent days haven't been released yet. Aside of that the 4.5.1 package isn't "outdated". New release will happen in the upcoming days.

**Comment by radiovisual** [comment]
@riklaunim , when I install the package via `pip install django-ckeditor`, I get version 4.x, but the latest version of this package is 5.x. I had to investigate because your latest commit: [Fix search empty result.](https://github.com/django-ckeditor/django-ckeditor/commit/9297c77284e00dd579cba662d7e0c9937a945415) does not appear in the version of the package that gets installed via pip. 

So does the version that pip install out of date, or am I missing something?

Thanks for the awesome work you do!

**Comment by riklaunim** [comment]
Yes, pip needs a new release. I'll have to check Django 1.9 too and then release.

**Comment by radiovisual** [comment]
Awesome, thanks! :+1:
