### ISSUE TITLE
404s when using ManifestFilesMixin

### ISSUE THREAD

**Issue by SteveByerly** [django-ckeditor/django-ckeditor#283]
I recently implemented the ManifestFilesMixin for my static files storage in my project. Everything works fine, but when ckeditor inits, it tries to load config.js and gets a 404. I'm having a hard time pinpointing where the issue is - either the staticfiles side in django, or in the the ckeditor.js itself.

The way I was able to bypass the problem was to update the staticfiles.json file to remove the hash from the ckeditor.js location: 
"ckeditor/ckeditor/ckeditor.js": "ckeditor/ckeditor/ckeditor.356423a8692e.js"
to
"ckeditor/ckeditor/ckeditor.js": "ckeditor/ckeditor/ckeditor.js"

I'm not really sure why this works, though. I'm going to keep digging, but was hoping someone would know the answer or lead me in the right direction.

**Comment by SteveByerly** [comment]
I found the issue to be related to ckeditor.js and its getUrl function. 

- When  you load the normal js file (ckeditor.js), all of the pathing for subsequent script loading (i.e. config.js) works as expected. The textareas load up normally.

- When you load the ckeditor.js file from the path found in the staticfiles.json file (ckeditor.12345.js), the getUrl function in the script breaks since the path for the file isn't in the expected format of `foo.js`. It replaces the location of the requested script with the current window's location. This causes config.js to load from `http://foo/config.js`  instead of `http://foo/static/config.js`

- I tried setting window.CKEDITOR_BASEPATH and CKEDITOR.basePath on load with my STATIC_URL. This fixed loading the config.js file, but it failed to load other files (contents.css, etc). For some reason, the ckeditor.js script kept resetting the basepath.

- My solution was to force the staticfiles.json file to not append the hash to the filename by subclassing the ManifestFilesMixin


```
class CustomManifestFilesMixin(ManifestFilesMixin):

    def hashed_name(self, name, content=None):
        hashed_name = super(CustomManifestFilesMixin, self).hashed_name(name, content=content)
        if 'ckeditor/ckeditor.js' in name:
            return name
        return hashed_name
```

**Comment by karolyi** [comment]
This is crazy. I'm running into the same problem, with using django-require2. Admins that use a CKEDITOR field break.

Fix this already!

**Comment by Kio** [comment]
I think problem in regular expression that is used in `CKEDITOR.basePath`: 
`var a = /(^|.*[\\\/])ckeditor\.js(?:\?.*|;.*)?$/i`
In `basePath()` if not defined `window.CKEDITOR_BASEPATH` we iterate over all script tags in head and сheck if they satisfy the regular expression.
Your solution is not the best, because the main reasone to use ManifestFilesMixin is to use HTTP headers Expires and Cache-Control, but in fact if you change ckeditor.js browser will not load new version of file.
A good solution to this problem would be to change this regular expression to match file name.
I used script tag before ckeditor.js to fix problem: 
`<script>window.CKEDITOR_BASEPATH = "{% static 'ckeditor/ckeditor/' %}";</script>` (you need to load static template tag).
Unfortunately you can not write this code to ckeditor-init.js or config.js because they load after ckeditor.js and in ckeditor.js script tries to load resources and gets an error.

ps: sorry for my english, not native speaker.

**Comment by karolyi** [comment]
@Kio moreover, you'll have to modify the admin templates in order to get your solution working.

Since properly handling the HTTP headers for the file should be eligible to handle the caching of the file, I prefer @SteveByerly 's solution.

**Comment by matthiask** [comment]
There's a documentation patch in #376 addressing this problem.
