### ISSUE TITLE
CKEDITOR_RESTRICT_BY_USER using a possibly mutable value

### ISSUE THREAD

**Issue by tisdall** [django-ckeditor/django-ckeditor#344]
Currently if you use `CKEDITOR_RESTRICT_BY_USER` to divide files according to users, it's done by using the username.  This may be fine for a lot of people, but there's nothing in Django that doesn't allow you to modify the username on a person.  So, if a person changes their username, all of their uploaded files will become orphaned.  Even worse, if another user changes their username to one previously used by another user then they'll gain access to those uploaded files.

#178 would allow using the `id` value which is not mutable.  Obviously that PR isn't suitable as-is, but something like that is needed if people are using a mutable "username" (or whatever is returned by `get_username()`).

**Comment by some1ataplace** [comment]
To use the id field rather than username for CKEDITOR_RESTRICT_BY_USER in django-ckeditor, you can modify the get_folder() method in your custom CKEditorUploadBackend class to use the user's id instead of their username. Here's an example:

1. Create a custom CKEditorUploadBackend class in your backends.py file:

```
from ckeditor_uploader.backends import CKEditorUploadBackend

class CustomCKEditorUploadBackend(CKEditorUploadBackend):
    def get_folder(self):
        user_id = self.request.user.id
        return f'{self.upload_to}/user_{user_id}'
```


2. In your settings.py file, specify your custom backend class as the UPLOADBACKEND:

```
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_UPLOAD_BACKEND = 'yourapp.backends.CustomCKEditorUploadBackend'
```


With this implementation, the user's uploaded files will be stored in a folder with their id rather than their username, preventing orphaned files if the user changes their username.
