### ISSUE TITLE
user with is_superuser can't browse or upload

### ISSUE THREAD

**Issue by karolyi** [django-ckeditor/django-ckeditor#385]
Hey,

when a user who only has the `is_superuser` property `True` and `is_staff` `False`, because of `staff_member_required` in the `urls.py`, a login redirect is served.

Please use another method to decide if the user can access the upload and browse views.

Cheers

**Comment by riklaunim** [comment]
Nope. If you want to change it do what the readme says - add those views urls directly in your urls.py with desired decorator. By default django-ckeditor is designed to be used in Django admin panel.

**Comment by karolyi** [comment]
You are assuming wrongly that I want to use the upload/browse functionality outside of the admin. A user who has `is_superuser` but has no `is_staff` can use the admin. In order for him to use those views, he **HAS** to set `is_staff` on himself.

Either the documentation, or the used decorator is wrong. By saying 'one who can use the admin', a user with only `is_superuser` set still can't use the upload views.

**Comment by riklaunim** [comment]
staff_member_required is the most common decorator for this type of checks. It can be a permission decorator - but them - which permission? the decorator is in urls.py so that it's easy to customize.

Initial version of django-ckeditor had nothing there and every site with configured django-ckeditor allowed anyone to upload nearly anything. By enforcing a staff decorator by default configuration this is prevented and when someone wants something else - notices possible security implications of such change.

There can be a better thing than staff_member_required, but it must be somewhat universal.

**Comment by karolyi** [comment]
Actually, the `staff_member_required` function is wrongly implemented here, so it's not really `django-ckeditor`'s fault.

[In here](https://github.com/django/django/blob/master/django/contrib/admin/views/decorators.py#L12), that condition should be an `or`, not an `and`.

I'll try to create an issue on that, until then what you could do is note this in the documentation.

**Comment by karolyi** [comment]
As you can see, @timgraham has told that the `staff_member_required` does not really reflect the admin access, also it's not necessarily used only for that, and I actually agree with him.

So, could you please use a different method for the admin check?

**Comment by riklaunim** [comment]
It could be a permission check.
