### ISSUE TITLE
CKEditor objects in django-ckeditor config

### ISSUE THREAD

**Issue by dryoma** [django-ckeditor/django-ckeditor#388]
Hi,

Trying to implement object format for allowedContent from [this example](http://docs.ckeditor.com/#!/guide/dev_disallowed_content-section-how-to-allow-everything-except...). However, this config:
```py
CKEDITOR_CONFIGS = {
    'default': {
        'scayt_autoStartup': True,
        # To make allowedContent work
        "removePlugins": "stylesheetparser",
        'allowedContent': {
            '$1': {
                'elements': 'CKEDITOR.dtd',
                'attributes': True,
                'styles': True,
                'classes': True
            }
        },
        'disallowedContent': 'script; *[on*]',
    }
}
```
just strips nearly everything from the output (and also the toolbar). With just a string value instead (like `'p; b; i;'`) `allowedContent` does work, as with
```py
        'allowedContent': {
            '$1': {
                'elements': 'b',
                'attributes': True,
                'styles': True,
                'classes': True
            }
        },
```
meaning it's `'CKEDITOR.dtd'` that the config wouldn't process and thus nothing gets allowed as a result.

Is there any solution for this?

**Comment by HoshiYamazaki** [comment]
Seems that this is still actual...

**Comment by some1ataplace** [comment]
The issue you're experiencing with the 'allowedContent' configuration in django-ckeditor is caused by a bug in the 'allowedContent' implementation.

To work around this bug, you can define a custom 'allowedContentRules' function in your CKEditor configuration that explicitly allows only the elements, attributes, styles, and classes that you want. Here is an example:

```
def allowed_content_rules():
    """
    Only allow basic HTML tags and attributes in CKEditor
    """
    return {
        '$1': {
            'elements': {
                '^': ['p', 'br', 'strong', 'em', 'u', 'ol', 'ul', 'li', 'a', 'img'],
                'img': [
                    'alt',
                    'src',
                    'height',
                    'width',
                    'style',
                ],
                'a': [
                    'href',
                    'target',
                    'style',
                ]
            },
            'attributes': {
                'img': ['alt', 'src', 'height', 'width', 'style'],
                'a': ['href', 'target', 'style'],
                'style': ['text-align'],
            },
            'styles':
  'text-align': '^((left)|(right)|(center))$',
            },
            'classes': True,
            'stylesCombo_stylesSet': 'default named-styles',
        }
    }

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Image', 'CodeSnippet'],
            ['Undo', 'Redo'],
            ['Maximize']
        ],
        'extraPlugins': 'codesnippet',
        'codeSnippet_theme': 'monokai_sublime',
        'width': '100%',
        'height': 300,
        'allowedContentRules': allowed_content_rules,
        'enterMode': 2,
        'entities': False,
        'basicEntities': False,
    }
}
```

The "allowedContent" setting is used to specify which HTML elements, attributes, styles, and classes are allowed in the CKEditor content.

In your current configuration, the "allowedContent" setting is set to allow only CKEDITOR.dtd elements, which may be too restrictive and cause the CKEditor toolbar to be stripped down.

To fix this, you can try updating the "allowedContent" setting to allow the elements, attributes, styles, and classes that you need for your content. For example, you can try setting it to allow basic formatting elements like "p", "b", and "i" as you mentioned in your second example.

Alternatively, you can try removing the "allowedContent" setting altogether and see if that resolves the issue. By default, CKEditor should allow a wide range of HTML elements, attributes, styles, and classes, so you may not need to specify them explicitly.
