### ISSUE TITLE
Specials characters

### ISSUE THREAD

**Issue by Ya2s** [django-ckeditor/django-ckeditor#396]
Hello,

When I display a text written with a TextField, there is a problem with specials characters because they are visibles like that : "&eacute;", "&nbsp;". What I want is "é", " ",...

So I show you my code, it's posible I forgot something...  : 

In my **settings.py** : 

CKEDITOR_UPLOAD_PATH = "uploads-ckeditor/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline','Format'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat']
        ]
    }
}

In **models.py** when I create a textField : 

class Groupe(models.Model) :
	...
	presentation = RichTextField(config_name='default',max_length=3001)
        ...
	
	class Meta :
		abstract = True

In a **template** when I display the text : 

...
<p class="col-md-12 col-sm-12 col-xs-6 orange"> 
		{{ projet.presentation|striptags|truncatechars:70 }} 
</p>
...

Have I did a mistake ? :(

**Comment by matthiask** [comment]
Apart from the fact that both versions of "e accent aigu" look the same to me I suspect it has to do with unicode normalization (NFKC vs NFKD). Some fonts are looking real bad when using the decomposed form. That's why we run all HTML entered through a normalizer (example: https://github.com/matthiask/html-sanitizer/blob/master/html_sanitizer/sanitizer.py#L275 )

Or maybe there's a different problem -- in this case please post screenshots :-)

**Comment by Ya2s** [comment]
Ola ola it seems complicated for my problem. I have this problem of "accents & co" just when a text is written with **RichTextField** ! 

A screenshot of a text :  http://hpics.li/1ab3162

**Comment by matthiask** [comment]
Ah... well those are simply HTML entities. You should probably `|safe` your HTML:
https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#safe

(Beware of XSS etc. though!)
