### ISSUE TITLE
A lightweight django-ckeditor

### ISSUE THREAD

**Issue by egonulates** [django-ckeditor/django-ckeditor#397]
I understand that the app "included all ckeditor language and plugin files to made everyone happy!". I don't need many of the plugins the app (django-ckeditor) comes with. It increases my "collectstatic" command to AWS S3 immensely (1 minute vs. 5-6 minutes). With lightweight editor I can have about 200 files, but current full editor have about 1126 files with all language and plugin files. 

Is there a way to select only the necessary plugins and languages?

**Comment by matthiask** [comment]
Currently there is no way to do this. But maybe something like https://github.com/jazzband/collectfast would help?

**Comment by gonulate** [comment]
Thanks for letting me know and referencing to 'collectfast'.

Just to understand the mechanics of installing django-ckeditor, it downloads the CKEditor files when I first install it or when I update the 'django-ckeditor'. So technically, I can remove the unwanted files/plugins from my virtual environment and they will not be updated until a fresh install (of 'django-ckeditor') or update, right?

**Comment by matthiask** [comment]
Yes, that's correct. OTOH I can't recommend modifying files inside the virtualenv :-) but if you know what you're doing you'll probably be fine.

**Comment by marfire** [comment]
Yes, 1126 mostly-unused static files is... too many. (And multiply that number by 2 or more if you're using `ManifestStaticFilesStorage`.)

Note that this bundling of the full package goes against [official ckeditor recommendations](http://docs.ckeditor.com/#!/guide/dev_howtos_basic_configuration):

> Remember that one of the most important CKEditor best practices is to customize your editor build with CKBuilder and remove unneeded functionality before it makes it to your package. It is a bad practice to download the Full package and then remove plugins or buttons in your configuration. You will only be loading unnecessary stuff without any good reason.

Given that, I think it's a good idea to at least support a way for people to substitute their own build if they like.

I was able to get this working by simply removing the bundled build and instead pointing `STATICFILES_DIRS` to my own build. I got rid of 1000 unused files that way. Of course, that's not a viable long-term solution since the bundled build will be restored on each update.

But I think this approach could be officially supported fairly easily. The idea is that you would split out the ckeditor code into its own Django app (still in this same project) who's only purpose is to have a `static` directory with the ckeditor code. To get the current behavior, then, the only change is that you would put both apps in your `INSTALLED_APPS`. To substitute your own build, you just remove the static ckeditor app from `INSTALLED_APPS` and instead use `STATICFILES_DIRS` to point to your custom build.

**Comment by riklaunim** [comment]
custom ckeditor in any source of static/ files would do (following the folders path). Decoupling ckeditor from the integration code is something I want to have. Bundled editor also requires package releases when there are some important ckeditor release just to ship the new JS code.

In the end there will likely be 3 django apps - JS editor, form field, form field with upload.

**Comment by marfire** [comment]
So you want to unbundle ckeditor entirely, and have each user provide their own? I think that's fine, though you might get some pushback from users who want things to "just work".

One option would be to split the ckeditor build (packaged as a Django app) into its own repository / pip install so users have the option to use it, and can use the versioning tools they're used to (pinning versions in pip, etc.). Someone would still have to maintain it, but at least it wouldn't be coupled with this package and would make releases more sensible.

**Comment by riklaunim** [comment]
No, just allow to enable/disable it by adding/removing from installed apps.

**Comment by dryoma** [comment]
Hey @riklaunim 
Any plans for implementing that?

**Comment by riklaunim** [comment]
If anything - it would be a separation of ckeditor from the django python package so that you could make your custom solution and version.

**Comment by dryoma** [comment]
That would be great. In a course of days multiple reasons emerged why we'd want to customize a CKEditor build/version. So having the ability to do so with django-ckeditor out of the box would be perfect.

**Comment by dryoma** [comment]
That would be great. In a course of days multiple reasons emerged why we'd want to customize a CKEditor build/version. So having the ability to do so with django-ckeditor out of the box would be perfect.

**Comment by matthiask** [comment]
Yes, that would probably be a good (configuration) option.

**Comment by some1ataplace** [comment]
To use a CDN like https://cdnjs.com/libraries/ckeditor instead of having to manage the static files yourself, you can modify the CKEDITOR_BASEPATH setting in your settings.py file.

Here's an example of how to use the CDN:

1. Add the ckeditor app to your INSTALLED_APPS setting in settings.py:

```
INSTALLED_APPS = [
    'ckeditor',
]
```


2. In your settings.py file, add the following CKEDITOR_BASEPATH setting:

`CKEDITOR_BASEPATH = '//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.16.1/'`


This sets the CKEDITOR_BASEPATH to the CDN URL for the version of CKEditor you want to use.

3. In your template, load the CKEditor JavaScript file:

```
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Page</title>
    <script src="{{ CKEDITOR_BASEPATH }}ckeditor.js"></script>
  </head>
  <body>
    <textarea name="mytextarea"></textarea>
    <script>
      CKEDITOR.replace('mytextarea');
    </script>
  </body>
</html>
```


This example shows how to load the CKEditor JavaScript file from the CDN by using the CKEDITOR_BASEPATH setting in the URL. The CKEDITOR.replace method is used to replace the <textarea> element with the CKEditor instance.

By using a CDN, you don't have to worry about managing the static files yourself and can rely on the CDN to serve the files for you.

***

Here's an example of how to use the CDN and make it work with RichTextField():

1. Add the ckeditor app to your INSTALLED_APPS setting in settings.py:

```
INSTALLED_APPS = [
    'ckeditor',
]
```


3. In your settings.py file, add the following CKEDITOR_BASEPATH and CKEDITOR_CONFIGS settings:

```
CKEDITOR_BASEPATH = '//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.16.1/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}
```


This sets the CKEDITOR_BASEPATH to the CDN URL for the version of CKEditor you want to use, and sets the default configuration for the CKEditor instance.

4. In your models.py file, use RichTextField():

```
from ckeditor.fields import RichTextField

class MyModel(models.Model):
    my_field = RichTextField()
```


5. In your admin.py file, use CKEditorWidget():

```
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget
from .models import MyModel

class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        RichTextField: {'widget': CKEditorWidget},
    }
    
admin.site.register(MyModel, MyModelAdmin)
```


This sets the widget for RichTextField to CKEditorWidget, which will use the CDN and default configuration specified in your settings.py file. Finally, it registers your model with the admin site using the custom admin class MyModelAdmin.
