### ISSUE TITLE
apps.py ( configuration )

### ISSUE THREAD

**Issue by burakk** [django-ckeditor/django-ckeditor#402]
Hi,

Is it possible to set ckeditor configuration in apps.py file as reccomended on django website?

**Comment by riklaunim** [comment]
If it's exposed to the global django.conf.settings then it should work.

**Comment by matthiask** [comment]
I don't think I'd put settings inside appconfigs, since django-ckeditor reads settings from `django.conf.settings` anyway. Putting settings in `apps.py` files just sounds like a way to hide settings instead of avoiding them altogether.

As long as Django doesn't move towards being settings-free I don't think there's a way to substantially improve things here.
