### ISSUE TITLE
pasting the image with content from word

### ISSUE THREAD

**Issue by singhprabhanshu** [django-ckeditor/django-ckeditor#412]
pasting the image with content from word to richtext field, only copy content not image

**Comment by singhprabhanshu** [comment]
in the prievious version of ckeditor, the image with content is copied to  the richtextField, but now it is not possible. the new version and the previous one both not supporting now the copy of image with the content of word file in ckeditor

**Comment by singhprabhanshu** [comment]
it depends on the browser and OS that is used. In ubuntu 17 , chromium and firefox have this problem but in ubuntu 16.04, chromium  and firefox has no any issue in copy and paste of content with image from word.

**Comment by riklaunim** [comment]
this is something likely not dependent on Python part, rather only ckeditor only.

**Comment by singhprabhanshu** [comment]
yes sir, it is not related to python only the problem is with the django-ckeditor which is not compatible with the browsers in ubuntu 17. how can we solve the problem of browser in ubuntu 17?

**Comment by riklaunim** [comment]
it's ckeditor and not django-ckeditor - this package is not responsible how ckeditor works. Also I don't remember if the ckeditor image upload plugin was even integrated with image copy paste or not.

If it worked with 16.04 but not 17.04 then likely CKEditor used some flash app to do it - since Flash is non-existent in modern browsers (updating 16.04 LTS browsers would also give you current ones without flash)

**Comment by singhprabhanshu** [comment]
ok thank you for the information
