### ISSUE TITLE
ckeditor works in local environment, but not in production

### ISSUE THREAD

**Issue by ephes** [django-ckeditor/django-ckeditor#433]
Hi *,

I'm trying to get ckeditor to work using the django cookiecutter template with docker. In the local development environment all works fine, but the production deployment doesn't work. In the javascript console I get following errors:
```
wersdoerfer.de/:1 Refused to execute script from 'https://wersdoerfer.de/blogs/ephes_blog/add/config.js?t=H4PG' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
wersdoerfer.de/:1 Refused to execute script from 'https://wersdoerfer.de/blogs/ephes_blog/add/lang/en.js?t=H4PG' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
ckeditor.8e9749424093.js:245 Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.d (ckeditor.8e9749424093.js:245)
    at f (ckeditor.8e9749424093.js:246)
    at Array.C (ckeditor.8e9749424093.js:246)
    at w (ckeditor.8e9749424093.js:246)
```

**Comment by ephes** [comment]
Ok, my fault. I forgot a $ at the end of an url pattern and therefore the current page was served, so the 'text/html' mime type was correct. But why is ckeditor searching for it's assets below the current url in the first place? /static/ckeditor works and when I add redirects in the app server, ckeditor now works. But I'd prefer to have ckeditor looking in /static/ckeditor instead of having redirects in the app server. Is there any way to tell ckeditor where the assets are?

**Comment by ephes** [comment]
Setting CKEDITOR_BASEPATH in a script tag worked, just had to read the documentation more carfully :).

**Comment by matthiask** [comment]
I've fixed this, but bungled the fix when removing the jQuery dependency from the JavaScript code.

The safest thing to do is what the documentation (https://github.com/django-ckeditor/django-ckeditor) says, set `window.CKEDITOR_BASEPATH = '/static/ckeditor/'` somewhere before the CKEditor JavaScript is included. The problem is that CKEditor cannot find its own location when using `ManifestStaticFilesStorage` because it only looks for `ckeditor.js`, not `ckeditor.****.js`.

**Comment by matthiask** [comment]
Too late ;)

**Comment by ephes** [comment]
Thanks for the explanation, didn't know that ManifestStaticFilesStorage caused the problem.

**Comment by elebumm** [comment]
Rebringing this back up since I came across this same issue. I had the error: `Uncaught TypeError: Cannot set property 'dir' of undefined` and I am using Django CMS. @ephes and @matthiask have the right answer but it's a little different under Django CMS. 

First go to your templates file and create an `admin` folder and inside of that folder create `base_site.html`. You will then paste this code into it:

```
{% extends "admin/base.html" %}{% load i18n staticfiles admin_style_tags %} {% block extrastyle %}{% include 'admin/inc/extrastyle.html' %}{% endblock %}
 {% block extrahead %}
<meta name="viewport" content="width=device-width,initial-scale=1" />


<script>window.CKEDITOR_BASEPATH = '/assets/ckeditor/ckeditor/';</script>


<link rel="stylesheet" type="text/css" href="{% static 'djangocms_admin_style/css/djangocms-admin.css' %}" /> {% if request.user.is_superuser %}{% render_update_notification %}{% endif %}
<script src="{% static 'djangocms_admin_style/js/dist/bundle.adminstyle.min.js' %}"></script> {% include 'admin/inc/extrahead.html' %}{% endblock %}

{% block title %}{% include 'admin/inc/title.html' %}{% endblock %}

{% block bodyclass %}{{ block.super }} djangocms-admin-style{% endblock %} {% block branding %}{% include 'admin/inc/branding.html' %}{% endblock %} {% block userlinks %}{% include 'admin/inc/userlinks.html' %}{{ block.super }}{% endblock %}
```

Keep in mind @ephes and @matthiask answer that I have divided in that code so you can insert where your files are. This worked for me and hopefully doesn't stop people from spending hours trying to solve this... like me. :cry:

**Comment by matthiask** [comment]
Thanks to #464 the docs now also contain a probably easier-to-follow suggestion than overriding `base_site.html`

**Comment by Nitesh-Singh-5** [comment]
I used ckeditor in my django project.It is working fine in local machine.But after deploying to web server it is not working. I can see the textarea without ckeditor tools.

**Comment by milopersic** [comment]
> 
@Nitesh-Singh-5 Did you ever figure out what was causing this?
