### ISSUE TITLE
Error code: uploadimage-config.

### ISSUE THREAD

**Issue by GembeJr** [django-ckeditor/django-ckeditor#463]
i got this error and how to resolve this?

![a](https://user-images.githubusercontent.com/7575645/35348885-05812638-016c-11e8-9252-c3c9ed6fd26e.png)

**Comment by yeyu1271** [comment]
have you solved the problem?

**Comment by some1ataplace** [comment]
views.py
```

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from ckeditor_uploader.views import upload as ckeditor_upload

@csrf_exempt
def upload(request):
    response = ckeditor_upload(request)
    if response.status_code == 200:
        # Customize the response data as needed
        data = {
            'uploaded': 1,
            'fileName': response.json['filename'],
            'url': response.json['url'],
        }
        return JsonResponse(data)
    else:
        return JsonResponse({'uploaded': 0})
```

This view imports the CKEditor image upload view from the "ckeditor_uploader" app and decorates it with the "@csrf_exempt" decorator to disable CSRF protection. It then calls the CKEditor upload view with the "request" object and checks if the response status code is 200. If the response is successful, it customizes the response data with the uploaded file name and URL and returns a JSON response with the "uploaded" flag set to 1. If the response is not successful, it returns a JSON response with the "uploaded" flag set to 0.

If you are encountering an "Error code: uploadimage-config" when uploading images in Django-CKEditor, it may be due to a misconfiguration in your CKEditor settings. Here are a few things you can check:

1. Verify that the "filebrowserUploadUrl" setting in your CKEditor configuration is set to the correct URL for image uploads. This should point to the URL where the CKEditor image upload view is located.

2. Check that the "filebrowserImageUploadUrl" setting in your CKEditor configuration is not set, as it is deprecated and can cause conflicts with the "filebrowserUploadUrl" setting.

3. Ensure that the CKEditor image upload view is properly configured in your Django project. You can check that the view is included in your project's URL configuration and that the URL matches the "filebrowserUploadUrl" setting in your CKEditor configuration.

4. Check that the CKEditor image upload view has the correct permissions set for uploading images. You may need to adjust the permissions in your Django project's settings or in the view itself.

# settings.py

INSTALLED_APPS = [
    # ...
    'ckeditor',
    'ckeditor_uploader',
    # ...
]

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['Image', 'Link', 'Unlink'],
            ['NumberedList', 'BulletedList', 'Blockquote'],
            ['RemoveFormat', 'Source']
        ],
        'extraPlugins': 'image2',
        'image_previewText': True,
        'filebrowserImageThumbWidth': 300,
        'filebrowserImageThumbHeight': 300,
        'filebrowserUploadUrl': '/ckeditor/upload/',
    }
}

# urls.py

from django.conf.urls import url
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    # ...
    url(r'^ckeditor/upload/', ckeditor_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    # ...
]
```

This configuration sets the "CKEDITOR_IMAGE_BACKEND" to "pillow" to enable thumbnail generation. It also includes settings for the CKEditor toolbar, image preview, thumbnail size, and upload URL. The "ckeditor_uploader" app is added to the "INSTALLED_APPS" and the corresponding URLs are added to the "urlpatterns" list.
