### ISSUE TITLE
Using editor changes the style of the template

### ISSUE THREAD

**Issue by AoiToShiro** [django-ckeditor/django-ckeditor#476]
Hello, beginner issue I'm afraid. This is the 3rd WYSIWIG editor I have installed and is the best so far in terms of ease of installation and use. However, When I go to use it on my blog app it completely changes the styling of the templates where the output is being displayed (I did see this behaviour with the two other WYSIWYG editors, amongst other strange issues that lead me to uninstall them). 

I'm now into my second day of trying to find out what the problem is and fix it, but I'm not getting very far, although, adding |safe to the template is what appears to trigger the change (I know I need |safe here as leaving the HTML is not an option). I have attached an image of what the page looks like before and after adding |safe: 
Before |safe
![image](https://user-images.githubusercontent.com/35370046/37419121-acefeed0-27ab-11e8-9d19-605eaebb24ed.png)

After |safe:
![image](https://user-images.githubusercontent.com/35370046/37419243-e5782240-27ab-11e8-80c8-155efb479aa3.png)

In the after |safe image the card has moved from being in the row down to the column and the text is red, even though it is set as black in the editor itself.

I am using Django 2.0.2 & Python 3.4.6. My styling uses Bootstrap 4, the list view of the blog is using cards in a 3 column x 4 row format. I am using a forloop to generate this.

I realise this is not necessarily specific to CKeditor given that I've seen this with other editors, but if you have any ideas that would really be appreciated as currently I'm getting fed up of banging my head against a brick wall. It's either a compatibility issue, or I'm missing something very simple.

**Comment by josylad** [comment]
I am currently facing this same issue. 
Is there a way to fix this??

**Comment by matthiask** [comment]
The editor uses (almost?) no CSS to style content in its editor area unless you are overriding it with `contentsCss`.

However, your frontend may have default styling e.g. for `<code>` blocks. The styling issue has almost certainly nothing to do with django-ckeditor, but is a result of some CSS you're using on your own site.

**Comment by josylad** [comment]
I found the problem.. the problem was that CKEditor was outputting various HTML tags on the page which was breaking the website and the |safe filter didn't help. 

I eventually figured it out and I am able to display the contents without any HTML tags and everything works fine now. 
There should be a filter that returns plain text for CKeditor, it will save people from a lot of worries.

**Comment by matthiask** [comment]
Hmm why would you use a rich text / HTML editor and not just a `<textarea>` if all you wanted was plain text?

**Comment by josylad** [comment]
Let's say I have a Django blog where I publish articles with images, bold text, italics and the likes using CKeditor but then on my home page, I want to display an excerpt of all my articles.  

**This excerpt should not have any HTML tags in it, just plain text!**

Do I need to add an extra field to my model just because I want to get plain text description?? 
it is counter-productive to do such; a friend recommended adding another model field for short description but I said NO. 

My rich text editor should be able to provide me with a plain text version for places where I don't need text styling and formatting.

**Comment by matthiask** [comment]
Ah alright.

I don't think it's the editor's job to do this though. Anyway, you've probably found Django's `|striptags` filter then https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#striptags

**Comment by josylad** [comment]
Yes, I found striptags filter and it helped except for "white spaces" ; so I combined it with the |safe filter and all tags are gone. 

so, `|striptags |safe` does the trick.
