### ISSUE TITLE
Plans about ckeditor 5

### ISSUE THREAD

**Issue by jiuri0624** [django-ckeditor/django-ckeditor#482]
有没有计划支持到ckeditor5，  5的操作编辑体验非常棒。

**Comment by riklaunim** [comment]
django-ckeditor has two parts - file upload/management via third party ckeditor plugin and a form field that initializes the editor itself. Moving to ckeditor5 we likely will loose current file management in favor of their build it simpler uploader. Form field integration can still be done. In the end it will be a major version bump, not fully backward compatible.

**Comment by riklaunim** [comment]
Didn't had the opportunity to check CkEditor 5 yet. This package started as a "ckeditor for django with file upload". Having that file upload is a rather big thing.

Also packaging a JS package into a Python package isn't the best thing and that should change as well.

**Comment by guettli** [comment]
I think the title of this issue should get updated. And then the duplicate #508 can be closed. AFAIK I can't do both.

**Comment by hashlash** [comment]
You might want to check this https://github.com/hvlads/django-ckeditor-5

**Comment by pulse-mind** [comment]
Hi,

First, thank you to all the contributors who work on this project. 

CKEditor 4 is supposed to be End Of Life in June 2023 (https://support.ckeditor.com/hc/en-us/articles/115005281629-How-long-will-CKEditor-4-be-supported-). So it become a critical problem for many users : security, stability, bugs...

Do you plan to to something ? may be merge with https://github.com/hvlads/django-ckeditor-5 where @hvlads did a very good job... ? 

Best regards,
Fred

**Comment by pulse-mind** [comment]
Yep, it is a good question. 
Some information about the licence : 

> CKEditor 5 is distributed under a GPL 2+ copyleft license. If you are not compatible with GPL 2+ license restrictions and wish to use our solutions

Which allow to do a lot of things.

**Comment by pulse-mind** [comment]
And a product which is not maintained is a problem, the first and the main reason is for security purpose, I would not start with and If I am already a user I would think to migrate to something else (same product with the current version of another product).

**Comment by goapunk** [comment]
@matthiask sorry for the dupe, I'll repost my question here: ckeditor4 is end of life since june 2023. Are there any plans to move to ckeditor5 ? Or would you be accepting PRs for that?

**Comment by matthiask** [comment]
I think so, yes. But I still have doubts regarding the licensing situation. Of course the GPL isn't the AGPL, but. If we bundle CKEditor 5, my understanding is that we'd have to change django-ckeditor's license, which in turn means that everybody distributing packages depending on django-ckeditor would have to think about their licensing as well. I'm not a lawyer, that isn't legal advice, but I would really want some clarifications here.

**Comment by matthiask** [comment]
This has gotten more important by the deprecation of CKEditor 4 (see for example #761) but it still won't happen. Since CKEditor 5 only has a GPL-licensed open source version django-ckeditor would also have to be licensed under the GPL, and in turn also all projects which use / link django-ckeditor, if they are distributed. At least that's my understanding of how this works. While I understand and appreciate the GPL I don't want to attempt  relicensing django-ckeditor under a license which makes some of my own open source work harder and less useful. 

I'm going to close this issue as not planned, and will point people towards https://github.com/hvlads/django-ckeditor-5 (the authors seem to have a different interpretation of the licensing issues)
