### ISSUE TITLE
how can i setup an inline-editor?

### ISSUE THREAD

**Issue by lifeyf** [django-ckeditor/django-ckeditor#483]
as the title says,how to do it?tried many times, except ignore the django-ckeditor i can not achieve it?thanks for answer

**Comment by riklaunim** [comment]
inline editor? In what context and where?

**Comment by spoonlyorange** [comment]
Hi,
I'm also trying to create an inline editor. I'm using it in a Django Model Form. A sample of the code I'm using to create the editor:
`title = forms.CharField(widget=CKEditorWidget(config_name='title'))`
It appears as a normal Editor field. I tried using the previous workaround from CKEditor 4.4:
```
    CKEDITOR.disableAutoInline = true;
    CKEDITOR.inline( 'id_name', {customConfig: "{% static 'js/title.js' %}"} );
```
but I get an error saying that 'id_name' is already in use:
`Uncaught The editor instance "id_name" is already attached to the provided element.`
I'm not sure if the inline editor is still available in Django CKEditor 5, but if it is, could you please detail how it is used?

Thanks,
Spoon

**Comment by lifeyf** [comment]
look at the ckeditor website, the inline-editor  works convenient and greatful ,so i want to setup it into my blogs，really! please show us an example,how to do it with django-ckeditor.
Thanks very much,
and, i found some setup does not work properly ,eg:
![ib 3242 vx70my k 0bprk](https://user-images.githubusercontent.com/24315133/43533632-dc5fb2cc-95e7-11e8-8311-770b0a2c7872.png)
Are all settings like
`config.name = 'value';`
could write into django settings.py like
`'name': 'value',`
I have tried to change it in config.js (in collected statics) but no effect at all, very confused.

best wishes  ,
thanks

**Comment by deanmcginndm** [comment]
I see there is pieces of information on update logs on the docs pages, but nothing concrete except the workaround mentioned above (which doesnt work, at least it doesnt for my configuration, might be worth you trying if youre just reading this)

**Comment by philgyford** [comment]
I can see one possibly relevant mention in the changelog, for v4.4.4: "Fixes for inline editor"

I'm *guessing* that this commit is what that refers to: https://github.com/django-ckeditor/django-ckeditor/commit/440cda35d2921dd6356a8e732a8e2a4bd188e601

But I'm not clear what that's doing, and it was so long ago (we're now at v6.5.1), that I'm not sure it's helpful for figuring this out.

I've tried editing a copy of [`ckeditor/ckeditor-init.js`](https://github.com/django-ckeditor/django-ckeditor/blob/master/ckeditor/static/ckeditor/ckeditor-init.js) and just changing `CKEDITOR.replace(...)` with `CKEDITOR.inline(...)` but it doesn't get run, because at [this point](https://github.com/django-ckeditor/django-ckeditor/blob/501fd12caf77a911e934ffef2cd2d7a9bb972eaa/ckeditor/static/ckeditor/ckeditor-init.js#L32) `t.getAttribute("data-processed")` is `"1"` instead of `"0"` for me. I guess it would need a more substantial rewrite to work.

(I'm using the `CKEditorWidget()` for a `TextField` in a ModelForm.)

**Comment by some1ataplace** [comment]
To enable an inline editor using django-ckeditor instead of the default CKEDITOR.replace, you can use the CKEDITOR_CONFIGS setting in your settings.py file to configure the CKEditor instance.

Here's an example of how to enable inline editing:

1. Add the ckeditor app to your INSTALLED_APPS setting in settings.py:

```
INSTALLED_APPS = [
    'ckeditor',
]
```


2. In your settings.py file, add the following CKEDITOR_CONFIGS setting:

```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'startupMode': 'inline',
    }
}
```


This sets the startupMode to 'inline', which enables inline editing.

3. In your template, load the CKEditor JavaScript and CSS files:

```
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Page</title>
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor.css' %}">
  </head>
  <body>
    <div contenteditable="true">My editable content</div>
    <script>
      CKEDITOR.inline('div');
    </script>
  </body>
</html>
```

***

To enable an inline editor with django-ckeditor, you can simply provide the CKEDITOR.inline configuration option in your template. Here's an example:

```
{% load static %}
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<textarea id="my-textarea">Hello, World!</textarea>

<script>
    // Initialize CKEditor
    CKEDITOR.inline('my-textarea', {
        toolbar: 'Basic',
        removeButtons: 'Underline,Strike,Subscript,Superscript'
    });
</script>
```


In this example, we're using the CKEDITOR.inline function to initialize an inline editor on a <textarea> element with an ID of "my-textarea". We're also providing a custom configuration object that specifies a basic toolbar and removes some unnecessary buttons.

Note that in order to use CKEDITOR.inline, you need to include both ckeditor-init.js and ckeditor.js in your template. These files are typically included in your base.html or header.html template, and loaded using Django's static template tag.


***

Override the ckeditor/ckeditor-init.js file in our project with our own version.

1. Create the ckeditor folder in your static folder and copy the ckeditor folder from django-ckeditor package into it
2. Create a new file called ckeditor-init.js in the same static/ckeditor folder
3. Edit ckeditor-init.js file and replace the CKEDITOR.replace call with CKEDITOR.inline. Here's an example of what it might look like:

```
function generateInlineEditor(id) {
    CKEDITOR.inline(id, {
        // Here you can customize editor settings
        removePlugins: 'elementspath',
        height: 200,
        toolbar: [
            {name: 'basicstyles', groups: ['basicstyles', 'cleanup'], items: ['Bold', 'Italic', 'Underline', 'Subscript', 'Superscript']},
            {name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align'], items: ['-', 'NumberedList','BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'AlignLeft', 'AlignCenter', 'AlignRight']},
            {name: 'links', items: ['Link', 'Unlink']},
            {name: 'others', items: ['Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor', 'Source']}
         ]
    });
}

// Initialize all inline editors with class 'inline-editor'
var editors = document.getElementsByClassName('inline-editor');
for (var i = 0; i < editors.length; i++) {
    generateInlineEditor(editors[i].getAttribute('id'));
}
```


4. In your Django template, include your ckeditor-init.js file, and add a div with a unique id and the "inline-editor" class to define your editable area

```
<head>
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
</head>


  <div id="my-editor" class="inline-editor">{{ my_content }}</div>
```
