### ISSUE TITLE
Support for Ckeditor 5?

### ISSUE THREAD

**Issue by emilpriver** [django-ckeditor/django-ckeditor#576]
First of all, great package! Well done.

Im just wondering if you maybe will add support for ckeditor 5 in the future? Or are you able to use ckeditor 5 today?

Dear,
Emil

**Comment by samuelhwilliams** [comment]
Really keen to get an update on this as well, because CKEditor 4 doesn't support CSP properly (script-src needs `unsafe-inline`), and there's seemingly little interest in updating CKEditor 4 to deal with that because it's meant to be handled better in v5 (https://github.com/ckeditor/ckeditor4/issues/829)

**Comment by matthiask** [comment]
Thanks for your report. Closing this issue since it is a duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/482
