### ISSUE TITLE
Nitpick: Avoid calling the widget a RichTextField

### ISSUE THREAD

**Issue by bobort** [django-ckeditor/django-ckeditor#585]
Rich text hearkens back the days of the rich text format (rtf) that was popular before HTML. I had to double-check that this widget does not, in fact, store data in rtf, but, rather, HTML. I'm new to CKEditor, so I am not sure what it is actually capable of.

I understand that this a nitpick and probably not worth the headache it will cause for legacy users. Nevertheless, I raise this issue to bring the naming of things to the forefront of our brains.

The django-tinymce package actually uses HTMLField, which is what it is. It's not a rich text field.

**Comment by prosper1** [comment]
Makes sense. It is already stored in the brain.

**Comment by matthiask** [comment]
You're not wrong.

I'm not sure the rename is worth the hassle. If you want to submit a backwards-compatible change renaming the field and allowing us to remove the `RichText*` aliasses later I'll probably merge it since I generally agree that naming is important. However, I certainly won't do the work myself.

(anecdotal data from https://support.microsoft.com/en-us/office/create-or-delete-a-rich-text-field-9f86237d-dbbc-4a85-b12c-9d8dca824630

![image](https://user-images.githubusercontent.com/2627/92325502-bbab4a80-f04b-11ea-8665-b7b9eb998796.png)
)

**Comment by bobort** [comment]
Well, I need updated myself. I had no idea that Access had switched over to HTML markup in their RichText widgets.
