### ISSUE TITLE
There were cross-site scripting vulnerabilities in 4.x prior to CKEditor 4.11.0.

### ISSUE THREAD

**Issue by zhao-dapeng** [django-ckeditor/django-ckeditor#607]
I'm sorry I didn't express myself clearly yesterday.

https://ckeditor.com/cke4/release/CKEditor-4.11.0

https://ckeditor.com/blog/CKEditor-5-v10.0.1-released/

The CKEditor 5 v10.0.1 release contains a security fix for the Link package, so it is strongly recommended that all CKEditor 5 installations that contain this Link be upgraded

**Comment by matthiask** [comment]
django-ckeditor bundles CKEditor 4.13.1 according to the CHANGELOG https://github.com/django-ckeditor/django-ckeditor/blob/master/CHANGELOG.rst

We should be safe then.

**Comment by ArturoQuintana** [comment]
Hello there,

I am having some security issues with django-ckeditor v5.9.0, and the point is that the user can insert javascript code and use it as a stored XSS.
I am wondering if there is any way to avoid HTML malicious content, javascript in this case.

Thanks in advance!

**Comment by matthiask** [comment]
You absolutely must filter user generated HTML on the server. There's no way around this, since people can submit what they want, e.g. after manually deactivating the CKEditor or simply by using the webdeveloper tools. I use my own https://pypi.org/project/html-sanitizer/ but there are also other options such as Mozilla bleach.
