### ISSUE TITLE
Image Drag & Drop Problem

### ISSUE THREAD

**Issue by iashutosh9119** [django-ckeditor/django-ckeditor#624]
Everything was working fine, but suddenly I am getting this error when I try to drag and drop images in Ckeditor. Previously all things were working fine. Didn't change anything, and don't know why this is happening. 
Any suggestions are welcomed.
Please Help!!!!
Note: I can easily upload image using the widget button in the toolbar. Only drag and drop is not working.
![Screenshot (41)](https://user-images.githubusercontent.com/46654708/91042733-e949ca00-e62f-11ea-9d23-b4fb2726efe5.png)

**Comment by iashutosh9119** [comment]
no one is replying ???? why????

**Comment by matthiask** [comment]
It's all volunteers doing the work here. That's the reason, nothing else. 

I'd suggest looking into the browser console, maybe there's a JavaScript error somewhere. Maybe drag-drop uses a different upload URL which isn't configured or even supported by django-ckeditor by default. I don't know.

Since I'm not personally interested in using the uploader part of django-ckeditor (see here why this is https://django-content-editor.readthedocs.io/en/latest/#about-rich-text-editors ) you seem to be on your own.

**Comment by iashutosh9119** [comment]
@matthiask It's strange as it was working fine previously and the site was in production for months without any change in its source code.
But still thanks for replying. 

Is there any alternative?

**Comment by bburan** [comment]
I'm getting something similar now. It seems to have to do with this particular call to the upload URL

```
[25/Nov/2020 17:08:15] "POST /ckeditor/upload/&responseType=json HTTP/1.1" 404 4867
[25/Nov/2020 17:08:49] "POST /ckeditor/upload/ HTTP/1.1" 200 131
Not Found: /ckeditor/upload/&responseType=json
```
