### ISSUE TITLE
Django-ckeditor  can create   catalogs?

### ISSUE THREAD

**Issue by McDingl** [django-ckeditor/django-ckeditor#634]
can create  catalog like this:
![image](https://user-images.githubusercontent.com/37035429/94097346-f63d2180-fe58-11ea-8ed0-486a607d0c7f.png)

1.title
   1.1 tilte
          .....
   1.2 title
         ......
2.title
3.title

**Comment by mikeromanov** [comment]
If I understood right, you want ckeditor_uploader (or other file browser attached to ckeditor) to upload images and other file types to some subdirectories of some directories. If so, it is completely possible. The default system is based on date and creates folder system like <year>/<month>/<day>. If you (like me) is not completely satisfied with this system and want to set up the folder structure more flexible, you can use file name generator (see ckeditor documentation). It can generate file names together with path, so that my folder tree now looks like <year>/<month>/<slugname>/. If you're interested, I can show you my file name generation function.
