### ISSUE TITLE
Editor fails to load - Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by cisarpavel** [django-ckeditor/django-ckeditor#717]
CKEditor fails to initiate. I experienced error similar to this https://github.com/ckeditor/ckeditor4/issues/5104.
Issue seems to be in initialising wysiwyg before ckeditor script is loaded and swapping order in https://github.com/django-ckeditor/django-ckeditor/blob/38dc127605ba7c085d0e03d8f55f912af14f4672/ckeditor/widgets.py#L33 helped.

**Comment by matthiask** [comment]
The problem is that `ckeditor-init.js` sets variables which have to be set *before* loading CKEditor under some circumstances, e.g. when using `ManifestStaticFilesStorage`, see https://github.com/django-ckeditor/django-ckeditor/blob/38dc127605ba7c085d0e03d8f55f912af14f4672/ckeditor/static/ckeditor/ckeditor-init.js#L3-L6 (The reason for this is that CKEditor searches the DOM for a `ckeditor.js` script and determines the path of plugins etc. depending on this. If it cannot find `ckeditor.js` then loading plugins etc. fails. Since `ManifestStaticFilesStorage` mangles the filename of assets CKEditor fails.

Maybe the code here https://github.com/django-ckeditor/django-ckeditor/blob/38dc127605ba7c085d0e03d8f55f912af14f4672/ckeditor/static/ckeditor/ckeditor-init.js#L9-L12 could be made smarter by additionally waiting on a CKEditor signal, maybe https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#event-loaded
