### ISSUE TITLE
Provide user to backend interface

### ISSUE THREAD

**Issue by Nigel2392** [django-ckeditor/django-ckeditor#767]
# Feature Request

I'm looking at this project and through the source of the uploader- but I can see there is only a path being passed for saving images.
This is kindof limiting.

Would it be possible to check for an attribute like `backend.takes_user`; and then act accordingly inside of the save method?
Maybe have it be a class attribute and pass the request object into the initialization of the backend.

This would then allow integration with some other projects, like Wagtail.

**Comment by matthiask** [comment]
Yes, that would definitely be possible.

I'm just not sure if further work on django-ckeditor is an excellent idea since django-ckeditor still uses CKEditor 4, but not the LTS version, so it has unfixable security vulnerabilities. The pinned issues here https://github.com/django-ckeditor/django-ckeditor/issues may offer some background and a better place for discussion about the future of this package.

**Comment by Nigel2392** [comment]
CKEditor5 doesn't seem like it was too hard to implement in https://github.com/hvlads/django-ckeditor-5

I might create a more "flexible" version for developers - work does not require me to license my code a specific way to I can happily abide to CKEditor5's GPL2 license.

**Comment by matthiask** [comment]
> I might create a more "flexible" version for developers - work does not require me to license my code a specific way to I can happily abide to CKEditor5's GPL2 license.

I like the ideas of the GPL and have been using it exclusively before starting to use Django many years ago. I also get why the CKEditor developers did it (see https://406.ch/writing/django-ckeditor/). I know that I can run my code on my server without publishing the (sometimes commercial/proprietary) code since I'm not actually shipping binaries to clients, just the results of running the code. I mean, CKEditor uses the GPL and not the AGPL after all. Stlil, it feels bad and I personally also want to conform with the spirit and not only the letter of the law. I don't have a problem with others reaching different conclusions for their projects but since django-ckeditor-5 exists I don't think evolving django-ckeditor makes a lot of sense. 

I always welcome the discussion, though.
